development: &development
  adapter: mysql2
  host: localhost
  username: ukirama
  password: "123"
  database: megacorp_development

test: &test
  adapter: mysql2
  host: localhost
  username: ukirama
  password: "123"
  database: megacorp_test

production: &production
  adapter: mysql2
  host: localhost
  database: megacorp_production
  username: ukirama
  password: "123"
